### ISSUE TITLE
Personalization via appending URL & updating value

### ISSUE THREAD

**Issue by vilav** [0x8890/simulacra#10]
Hi there!

Newbie here. I've been thinking about a use case to pseudo-personalize a webpage where if the url is:
http://www.website.com/welcome=FirstName

Then the page can pick up the "FirstName" value and pass the data into a `<p>` tag
Can the Simulacra plugin be used for this sort of use case?

Also, I've done some research and apparently JS based binding is prone to XSS vulnerabilities. Any thoughts on that?

Thanks
vilav

**Comment by 0x8890** [comment]
Yes, in the bound data object it would look something like this:

```js
var data = {
  name: window.location.toString().match(/welcome=+(.*)/)[1]
}
```

This library has nothing to do with XSS since there's *absolutely no networking code*. I think you misunderstand the scope of this library, it's very limited.
