### ISSUE TITLE
String output

### ISSUE THREAD

**Issue by 0x8890** [0x8890/simulacra#12]
Perhaps there should be a reduced use case for server-side rendering. Basically, all that it needs to do is output a string, without worrying about data mutation. `jsdom` could help here in keeping the API compatible in Node.js. A potential bottleneck with this approach is the initial time it takes to get a new instance of `jsdom`.

**Comment by michaelrhodes** [comment]
These [benchmarks](https://github.com/fgnass/dombench) might be of interest to you. I swapped out `jsdom` for `domino` in a module of mine a while back, and I’ve been really happy with the results.

**Comment by 0x8890** [comment]
Looks nice. I'm now thinking that the server-side DOM implementation should be separate from this library, though an example of server-side rendering should be included, probably using `domino`. Thanks for the tip.

**Comment by 0x8890** [comment]
Domino turns out to be very nice, I added [an example in the readme](https://github.com/0x8890/simulacra#server-side-rendering). There was only one problem, it doesn't implement `Node.prototype.contains`, so I added a workaround using `TreeWalker` if it's missing.

**Comment by michaelrhodes** [comment]
Very nice! Glad I could be of help. :)
