### ISSUE TITLE
Array of objects?

### ISSUE THREAD

**Issue by thinkcontext** [0x8890/simulacra#13]
Is it possible to render an array of objects?  Something like this:

    <template id="params">
      <ul class="a">
        <li>
          <span class="k1"></span>
          <span class="k2"></span>
        </li>
      </ul>
    </template>

    var data = {
      a: [{k1:'a', k2:'1'},{k1:'b',k2:'2'}]
    };
    function $ (s) { return fragment.querySelector(s) };

    var bindings = bind(fragment, {
      a: bind($('.a'), [bind($('.k1')), bind($('.k2'))])
    });

Thanks!

**Comment by 0x8890** [comment]
Yep, even in the example given on the project page, you can do something like this:

```js
data.details = [{vendor:'a',size:[1,2,3]},{vendor:'b',size:[4,5,6]}]
```

Simulacra.js internally treats every value as an array, so it doesn't matter if your values are arrays or not. This means that assigning `"abc"` and `["abc"]` does not mutate the DOM.
