### ISSUE TITLE
Under The Hood: Template tag?

### ISSUE THREAD

**Issue by james2doyle** [0x8890/simulacra#2]
You mentioned in the README that "it works in IE9+ with a WeakMap polyfill" but it seems like the `template` tag [requires a pretty new browser](http://caniuse.com/#search=template).

Did I miss something, or is the `template` tag support not a problem?

**Comment by 0x8890** [comment]
It's not a problem because using the `<template>` tag is optional. However, it is optimal to use it since its contents are not rendered by default. Hopefully that answers your question?

**Comment by james2doyle** [comment]
Oh ok. So you are using the `template` tag as an arbitrary container for the HTML?

**Comment by 0x8890** [comment]
Yup, it may as well be a `<div>` or generated programmatically as long as its a DOM Node.

**Comment by james2doyle** [comment]
OK nice. Thanks
