### ISSUE TITLE
Order of objects in arrays (rendered via <ul>) is not maintained.

### ISSUE THREAD

**Issue by Blechhirn** [0x8890/simulacra#5]
Just tried mutating a bound array item. The change is reflected, but the order of items in the rendered result does not match the one in the array anymore.

Here is a codepen that demonstrates the issue: http://codepen.io/anon/pen/XmwJBd

Is that the expected behavior or do I use the API in the wrong way?

**Comment by 0x8890** [comment]
whoops, definitely a bug.

**Comment by 0x8890** [comment]
This commit should fix it: https://github.com/0x8890/simulacra/commit/fe62be3c86cf7f1cb208dff606d1e41eb6b4d655 can you confirm?

**Comment by 0x8890** [comment]
I just checked your example again, and the latest release seems to have fixed it.

**Comment by Blechhirn** [comment]
Very nice! Fixed indeed.
