### ISSUE TITLE
event bindings lost in simulacra

### ISSUE THREAD

**Issue by BenjaminVerble** [0x8890/simulacra#8]
while working with simulacra, I discovered that I was not able to add event listeners to elements before inserting them into the dom. Is this as-designed? If so, what would the suggested pattern be for dealing with event bindings? This is what I am attempting: https://gist.github.com/BenjaminVerble/a0cdfbced1d5865df670

this is not critical to a project or anything. I was just curious and interested in simulacra. I like working closer to the dom api.

**Comment by 0x8890** [comment]
What does `$button` refer to in your example?

Someone put together a todo list example: https://github.com/marksteve/todo-simulacra/blob/gh-pages/index.js

Basically the way to do it is to pass a second argument (function) to simulacra which manipulates the node before appending it.

**Comment by BenjaminVerble** [comment]
$button is on line 13 of the gist

thank you for the explanation
